#!/usr/bin/env node
// Generate the specialist module from config/specialists.json (SMC-M03 plan §2.2), after validating the registry
// against config/schemas/specialists.schema.json. The same module is written twice: into the dsh bundle, which derives
// its specialist role presets from it (the bundle archive is self-contained), and into this package, where the API
// resolves research admission against it. The registry is the one source: an id, route or tool policy is never restated.
//   node scripts/generate-specialists.ts          write both specialists.generated.ts files
//   node scripts/generate-specialists.ts --check  fail if the registry is invalid or the module is out of date
//   node scripts/generate-specialists.ts --registry <file>  only validate another registry file (tests)
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { Ajv2020 } from 'ajv/dist/2020.js'

interface Specialist {
  id: string
  family: string
  task_kind: string
  outputs: string[]
  route: string
  native_tools: string[]
  prompt_sections?: string[]
  skills?: string[]
  references?: string[]
  image_input?: boolean
}

const root = join(dirname(fileURLToPath(import.meta.url)), '..', '..', '..')
const alternate = process.argv.indexOf('--registry')
const registryPath = alternate === -1 ? join(root, 'config', 'specialists.json') : (process.argv[alternate + 1] ?? '')
const schemaPath = join(root, 'config', 'schemas', 'specialists.schema.json')
const targets = [
  join(root, 'packages', 'dsh-bundle', 'src', 'specialists.generated.ts'),
  join(root, 'packages', 'contracts', 'src', 'specialists.generated.ts'),
]

const readJson = (path: string): unknown => JSON.parse(readFileSync(path, 'utf8')) as unknown
const quote = (value: string) => `'${value}'`

/**
 * The registry's problems beyond its schema: duplicate ids, a PDF output without the tool that renders it, the
 * render inspector without the renderer (it reads PDF renders only, S5b), and (SDD-01) a role whose tools cross into
 * another family's: a designer never holds research_* or review_* tools, a reviewer only review_* tools.
 */
function problems(specialists: readonly Specialist[]): string[] {
  const found: string[] = []
  const seen = new Set<string>()
  for (const s of specialists) {
    if (seen.has(s.id)) found.push(`${s.id} is registered twice`)
    seen.add(s.id)
    const renders = s.native_tools.includes('research_render_pdf')
    if (s.outputs.includes('pdf') !== renders) {
      found.push(`${s.id}: a PDF output and the research_render_pdf tool go together`)
    }
    if (s.native_tools.includes('research_inspect_output') !== renders) {
      found.push(`${s.id}: the research_inspect_output and research_render_pdf tools go together`)
    }
    const own = s.task_kind === 'design' ? 'design_' : s.task_kind === 'design_review' ? 'review_' : null
    const foreign = own === null ? [] : s.native_tools.filter((t) => !t.startsWith(own))
    if (foreign.length > 0) found.push(`${s.id}: tools of another role (${foreign.join(', ')})`)
  }
  return found
}

function load(): Specialist[] {
  // oxlint-disable-next-line typescript/no-unsafe-type-assertion -- the repository's own schema file; Ajv strict mode checks it
  const schema = JSON.parse(readFileSync(schemaPath, 'utf8')) as Record<string, unknown>
  const validate = new Ajv2020({ allErrors: true, strict: true }).compile<{ specialists: Specialist[] }>(schema)
  const registry = readJson(registryPath)
  if (!validate(registry)) {
    const detail = (validate.errors ?? []).map((e) => `${e.instancePath || '/'} ${e.message ?? ''}`).join('; ')
    throw new Error(`${registryPath} does not match its schema: ${detail}`)
  }
  const { specialists } = registry
  const found = problems(specialists)
  if (found.length > 0) throw new Error(`${registryPath}: ${found.join('; ')}`)
  return specialists
}

function generated(specialists: readonly Specialist[]): string {
  const entries = specialists.map((s) =>
    [
      '  {',
      `    id: ${quote(s.id)},`,
      `    family: ${quote(s.family)},`,
      `    outputs: [${s.outputs.map(quote).join(', ')}],`,
      `    route: ${quote(s.route)},`,
      `    nativeTools: [${s.native_tools.map(quote).join(', ')}],`,
      // SDD-01's fields, only where the registry sets them: a research row is generated exactly as before.
      ...(s.task_kind === 'research' ? [] : [`    taskKind: ${quote(s.task_kind)},`]),
      ...(s.prompt_sections ? [`    promptSections: [${s.prompt_sections.map(quote).join(', ')}],`] : []),
      ...(s.skills ? [`    skills: [${s.skills.map(quote).join(', ')}],`] : []),
      ...(s.references ? [`    references: [${s.references.map(quote).join(', ')}],`] : []),
      ...(s.image_input === undefined ? [] : [`    imageInput: ${String(s.image_input)},`]),
      '  },',
    ].join('\n'),
  )
  return [
    '// Generated by packages/contracts/scripts/generate-specialists.ts from config/specialists.json; do not edit.',
    '',
    '/** The specialist roles of the registry: what the bundle composes for each (id, route, native tool policy). */',
    'export const SPECIALISTS = [',
    ...entries,
    '] as const',
    '',
    "export type SpecialistId = (typeof SPECIALISTS)[number]['id']",
    '',
  ].join('\n')
}

if (alternate !== -1) {
  load()
  console.log(`${registryPath} is a valid specialist registry`)
  process.exit(0)
}

const expected = generated(load())
const stale = targets.filter((target) => !existsSync(target) || readFileSync(target, 'utf8') !== expected)

if (!process.argv.includes('--check')) {
  for (const target of stale) writeFileSync(target, expected)
  console.log(stale.length > 0 ? `wrote ${stale.join(', ')}` : 'specialist modules up to date')
} else if (stale.length > 0) {
  console.error(`Stale specialist module: ${stale.join(', ')}; run \`pnpm --filter @sophia/contracts generate\``)
  process.exit(1)
} else {
  console.log('Specialist modules match config/specialists.json')
}
