#!/usr/bin/env node
// Generate the dsh bundle's runtime wire module from openapi/openapi.json (amendment A04): the types and
// standalone validators of the /v1/runtime/* shapes, so the bridge validates exactly what the API does.
// The bundle ships inside the runtime artifact with no dependencies, so the output must need none:
// no format keywords, `unicode: false` (no ucs2length helper), and any remaining require() fails here.
//   node scripts/generate-runtime-wire.ts          write packages/dsh-bundle/src/runtime-wire*.generated.ts
//   node scripts/generate-runtime-wire.ts --check  fail if either file is out of date
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { Ajv } from 'ajv'
import standaloneCode from 'ajv/dist/standalone/index.js'
import { componentSchemas, openapi } from '../src/index.ts'
import { typesFromOpenApi, type OpenApi } from '../src/openapi-types.ts'

/** Component schemas the bridge reads or writes, in dependency order for the types file. */
const SCHEMAS = [
  'RuntimeWorkBinding',
  'RuntimeCommand',
  'RuntimeReceipt',
  'RuntimeObservation',
  'RuntimeHello',
  'RuntimeServiceBinding',
  'RuntimeHelloReply',
  'RuntimeCommandBatch',
  'RuntimeReady',
] as const
/** What the bridge validates at runtime: every reply it reads, each command, and what it sends. */
const VALIDATED = [
  'RuntimeCommand',
  'RuntimeHelloReply',
  'RuntimeCommandBatch',
  'RuntimeReceipt',
  'RuntimeObservation',
  'RuntimeHello',
  'RuntimeReady',
] as const

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const bundle = join(root, '../dsh-bundle/src')
const targets = {
  types: join(bundle, 'runtime-wire-types.generated.ts'),
  code: join(bundle, 'runtime-wire.generated.ts'),
}
const HEADER =
  '// Generated by packages/contracts/scripts/generate-runtime-wire.ts from packages/contracts/openapi/openapi.json (A04); do not edit.'

const wanted: ReadonlySet<string> = new Set(SCHEMAS)

/** ajv/dist/runtime/ucs2length (Ajv 8.20.0) as an expression. */
const UCS2LENGTH = `(function ucs2length(str) {
  const len = str.length;
  let length = 0;
  let pos = 0;
  let value;
  while (pos < len) {
    length++;
    value = str.charCodeAt(pos++);
    if (value >= 0xd800 && value <= 0xdbff && pos < len) {
      value = str.charCodeAt(pos);
      if ((value & 0xfc00) === 0xdc00) pos++;
    }
  }
  return length;
})`

function generatedTypes(): string {
  const doc: OpenApi = {
    components: {
      schemas: Object.fromEntries(
        SCHEMAS.map((name) => {
          const schema = openapi.components.schemas[name]
          if (!schema) throw new Error(`${name} is missing from the contract`)
          return [name, schema]
        }),
      ),
    },
    paths: {},
  }
  // The generic generator also emits an empty `Operations` interface; the bundle has no use for it.
  return typesFromOpenApi(doc, HEADER).replace(/export interface Operations \{\n\}\n$/, '')
}

function generatedCode(): string {
  const ajv = new Ajv({
    schemas: componentSchemas().filter((s) => wanted.has(s.$id)),
    strict: true,
    allErrors: false,
    code: { source: true, esm: true },
  })
  const names = Object.fromEntries(VALIDATED.map((name) => [`validate${name}`, `${name}#`]))
  const code = standaloneCode
    .default(ajv, names)
    .replace(/^"use strict";/, '')
    // Ajv's own helper, inlined verbatim: string lengths count code points exactly as the API's Ajv does.
    .replaceAll('require("ajv/dist/runtime/ucs2length").default', UCS2LENGTH)
  const runtime = [...code.matchAll(/require\("([^"]+)"\)/g)].map((m) => m[1])
  if (runtime.length > 0) throw new Error(`the runtime wire code would need ${runtime.join(', ')}`)
  const typed = VALIDATED.map((name) => `  ${name}: validate${name} as unknown as WireValidator<Types.${name}>,`).join(
    '\n',
  )
  return [
    HEADER,
    '// @ts-nocheck -- Ajv standalone output; the typed table at the end is what the bridge imports.',
    "import type * as Types from './runtime-wire-types.generated.js'",
    '',
    code.trim(),
    '',
    '/** A generated validator: a type guard that leaves its failures on `errors`. */',
    'export interface WireValidator<T> {',
    '  (value: unknown): value is T',
    '  errors?: ReadonlyArray<{ instancePath: string; message?: string }> | null',
    '}',
    '',
    'export const wire = {',
    typed,
    '} as const',
    '',
  ].join('\n')
}

const expected = { types: generatedTypes(), code: generatedCode() }
const KINDS = ['types', 'code'] as const
const stale = KINDS.filter((k) => !existsSync(targets[k]) || readFileSync(targets[k], 'utf8') !== expected[k])

if (!process.argv.includes('--check')) {
  for (const k of stale) writeFileSync(targets[k], expected[k])
  console.log(stale.length > 0 ? `wrote ${stale.map((k) => targets[k]).join(', ')}` : 'runtime wire up to date')
} else if (stale.length > 0) {
  console.error('The dsh bundle runtime wire module is stale; run `pnpm --filter @sophia/contracts generate`')
  process.exit(1)
} else {
  console.log('Runtime wire module matches OpenAPI')
}
