#!/usr/bin/env node
// Generate src/generated-types.ts from openapi/openapi.json (the pack contract plus amendments/).
//   node scripts/generate-types.ts          write src/generated-types.ts
//   node scripts/generate-types.ts --check  fail if the file is out of date
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { typesFromOpenApi, type OpenApi } from '../src/openapi-types.ts'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const target = join(root, 'src/generated-types.ts')
// oxlint-disable-next-line typescript/no-unsafe-type-assertion -- the package's own OpenAPI file, checked against pack + amendments
const doc = JSON.parse(readFileSync(join(root, 'openapi/openapi.json'), 'utf8')) as OpenApi
const text = typesFromOpenApi(
  doc,
  '/** Generated by packages/contracts/scripts/generate-types.ts from openapi/openapi.json (pack + amendments); do not edit. */',
)

if (!process.argv.includes('--check')) {
  writeFileSync(target, text)
} else if (existsSync(target) && readFileSync(target, 'utf8') === text) {
  console.log('Generated API types match OpenAPI')
} else {
  console.error('Generated API types are out of date: run pnpm --filter @sophia/contracts generate')
  process.exit(1)
}
