#!/usr/bin/env node
// Generate the dsh bundle's specialist module from config/specialists.json (SMC-M03 plan §2.2), after validating the
// registry against config/schemas/specialists.schema.json. The bundle derives its specialist role presets from the
// module, so the registry is the one source: a specialist's id, route and native tool policy are never restated.
//   node scripts/generate-specialists.ts          write packages/dsh-bundle/src/specialists.generated.ts
//   node scripts/generate-specialists.ts --check  fail if the registry is invalid or the module is out of date
//   node scripts/generate-specialists.ts --registry <file>  only validate another registry file (tests)
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { Ajv2020 } from 'ajv/dist/2020.js'

interface Specialist {
  id: string
  family: string
  task_kind: string
  outputs: string[]
  route: string
  native_tools: string[]
}

const root = join(dirname(fileURLToPath(import.meta.url)), '..', '..', '..')
const alternate = process.argv.indexOf('--registry')
const registryPath = alternate === -1 ? join(root, 'config', 'specialists.json') : (process.argv[alternate + 1] ?? '')
const schemaPath = join(root, 'config', 'schemas', 'specialists.schema.json')
const target = join(root, 'packages', 'dsh-bundle', 'src', 'specialists.generated.ts')

const readJson = (path: string): unknown => JSON.parse(readFileSync(path, 'utf8')) as unknown
const quote = (value: string) => `'${value}'`

/** The registry's problems beyond its schema: duplicate ids, and a PDF output without the tool that renders it. */
function problems(specialists: readonly Specialist[]): string[] {
  const found: string[] = []
  const seen = new Set<string>()
  for (const s of specialists) {
    if (seen.has(s.id)) found.push(`${s.id} is registered twice`)
    seen.add(s.id)
    const renders = s.native_tools.includes('research_render_pdf')
    if (s.outputs.includes('pdf') !== renders) {
      found.push(`${s.id}: a PDF output and the research_render_pdf tool go together`)
    }
  }
  return found
}

function load(): Specialist[] {
  // oxlint-disable-next-line typescript/no-unsafe-type-assertion -- the repository's own schema file; Ajv strict mode checks it
  const schema = JSON.parse(readFileSync(schemaPath, 'utf8')) as Record<string, unknown>
  const validate = new Ajv2020({ allErrors: true, strict: true }).compile<{ specialists: Specialist[] }>(schema)
  const registry = readJson(registryPath)
  if (!validate(registry)) {
    const detail = (validate.errors ?? []).map((e) => `${e.instancePath || '/'} ${e.message ?? ''}`).join('; ')
    throw new Error(`${registryPath} does not match its schema: ${detail}`)
  }
  const { specialists } = registry
  const found = problems(specialists)
  if (found.length > 0) throw new Error(`${registryPath}: ${found.join('; ')}`)
  return specialists
}

function generated(specialists: readonly Specialist[]): string {
  const entries = specialists.map((s) =>
    [
      '  {',
      `    id: ${quote(s.id)},`,
      `    family: ${quote(s.family)},`,
      `    outputs: [${s.outputs.map(quote).join(', ')}],`,
      `    route: ${quote(s.route)},`,
      `    nativeTools: [${s.native_tools.map(quote).join(', ')}],`,
      '  },',
    ].join('\n'),
  )
  return [
    '// Generated by packages/contracts/scripts/generate-specialists.ts from config/specialists.json; do not edit.',
    '',
    '/** The specialist roles of the registry: what the bundle composes for each (id, route, native tool policy). */',
    'export const SPECIALISTS = [',
    ...entries,
    '] as const',
    '',
    "export type SpecialistId = (typeof SPECIALISTS)[number]['id']",
    '',
  ].join('\n')
}

if (alternate !== -1) {
  load()
  console.log(`${registryPath} is a valid specialist registry`)
  process.exit(0)
}

const expected = generated(load())
const stale = !existsSync(target) || readFileSync(target, 'utf8') !== expected

if (!process.argv.includes('--check')) {
  if (stale) writeFileSync(target, expected)
  console.log(stale ? `wrote ${target}` : 'specialist module up to date')
} else if (stale) {
  console.error('The dsh bundle specialist module is stale; run `pnpm --filter @sophia/contracts generate`')
  process.exit(1)
} else {
  console.log('Specialist module matches config/specialists.json')
}
