#!/usr/bin/env node
// Generate standalone validators for the responses a client reads, from openapi/openapi.json.
// Ajv compiles them here, with the API's own options, so no browser needs Ajv or eval at runtime.
//   node scripts/generate-validators.ts          write src/generated/validators.js and .d.ts
//   node scripts/generate-validators.ts --check  fail if either file is out of date
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { _, Ajv } from 'ajv'
import addFormats from 'ajv-formats'
import standaloneCode from 'ajv/dist/standalone/index.js'
import { componentSchemas } from '../src/index.ts'

/** Component schema → exported validator. Only what a client parses from the wire. */
const EXPORTS = [
  'Snapshot',
  'Receipt',
  'ProjectCreated',
  'Error',
  'Event',
  'CursorAdvance',
  'RoomToken',
  'ExchangeReceipt',
  'Invitation',
  'InvitationList',
  'InvitationPreview',
  'InvitationAccepted',
  'LobbyEntry',
  'RoomSession',
  'Membership',
] as const

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const targets = { code: join(root, 'src/generated/validators.js'), types: join(root, 'src/generated/validators.d.ts') }
const HEADER =
  '// Generated by packages/contracts/scripts/generate-validators.ts from openapi/openapi.json; do not edit.'

/** The API's Ajv options (apps/api/src/app.ts) plus the same full format set Fastify installs. */
function compiler(): Ajv {
  const ajv = new Ajv({
    schemas: componentSchemas(),
    strict: true,
    allErrors: false,
    removeAdditional: false,
    coerceTypes: false,
    useDefaults: false,
    code: { source: true, esm: true },
  })
  addFormats.default(ajv, { mode: 'full' })
  // ajv-formats emits require() for format functions; name an ES import instead.
  ajv.opts.code.formats = _`fullFormats`
  return ajv
}

function generatedCode(): string {
  const names = Object.fromEntries(EXPORTS.map((name) => [`validate${name}`, `${name}#`]))
  const code = standaloneCode.default(compiler(), names)
  const runtime = [...code.matchAll(/require\("([^"]+)"\)/g)].map((m) => m[1])
  if (runtime.length > 0) throw new Error(`unexpected runtime require(s) in generated code: ${runtime.join(', ')}`)
  const body = code.replace(/^"use strict";/, '')
  return `${HEADER}\nimport { fullFormats } from 'ajv-formats/dist/formats.js'\n${body}\n`
}

function generatedTypes(): string {
  const imports = EXPORTS.map((name) => (name === 'Error' ? 'Error as ErrorBody' : name)).join(', ')
  const lines = EXPORTS.map(
    (name) => `export declare const validate${name}: ValidateFunction<${name === 'Error' ? 'ErrorBody' : name}>`,
  )
  return [
    HEADER,
    "import type { ValidateFunction } from 'ajv'",
    `import type { ${imports} } from '../generated-types.ts'`,
    '',
    ...lines,
    '',
  ].join('\n')
}

const expected = { code: generatedCode(), types: generatedTypes() }
const KINDS = ['code', 'types'] as const
const stale = KINDS.filter((k) => !existsSync(targets[k]) || readFileSync(targets[k], 'utf8') !== expected[k])

if (!process.argv.includes('--check')) {
  for (const k of stale) writeFileSync(targets[k], expected[k])
  console.log(stale.length > 0 ? `wrote ${stale.map((k) => targets[k]).join(', ')}` : 'validators up to date')
} else if (stale.length > 0) {
  console.error('Generated validators are stale; run `pnpm --filter @sophia/contracts generate`')
  process.exit(1)
} else {
  console.log('Generated validators match OpenAPI')
}
