// Generated by packages/contracts/scripts/generate-runtime-wire.ts from packages/contracts/openapi/openapi.json (A04); do not edit.
/** Format/pattern constraints are runtime validation obligations, not encoded by string types. */
export type RuntimeWorkBinding = { "projectId": string; "goalId": string; "goalRevision": number; "attemptId": string; "resourceId": string; "authorityEpoch": number; "runtimeUnitId": string; };
export type RuntimeCommand = { "schema": "sophia.runtime-command.v1"; "commandId": string; "binding": RuntimeWorkBinding; "kind": "create" | "resume" | "input" | "steer" | "hold" | "stop" | "inspect"; "expectedNativeSessionId": string | null; "contextPacketId": string | null; "payload": { "text"?: string; "role"?: string; }; };
export type RuntimeReceipt = { "commandId": string; "attemptId": string; "stage": "delivered" | "incorporation_observed" | "checked" | "rejected" | "failed" | "outcome_unknown"; "nativeSessionId": string | null; "nativeSequence": number | null; "evidenceRefs": ReadonlyArray<string>; "observedAt": string; "reason": string | null; };
export type RuntimeObservation = { "runtimeUnitId": string; "attemptId": string; "nativeSessionId": string; "nativeSeq": number; "type": string; "durable": true; "data": unknown; };
export type RuntimeHello = { "bundle": string; "protocolVersion": 1; "dshVersion": string; };
export type RuntimeServiceBinding = { "attemptId": string; "nativeSessionId": string; "authorityEpoch": number; "state": "active" | "held" | "stopped"; };
export type RuntimeHelloReply = { "projectId": string; "leaseId": string; "authorityEpoch": number; "bindings": ReadonlyArray<RuntimeServiceBinding>; "cursor": number; };
export type RuntimeCommandBatch = { "commands": ReadonlyArray<{ "seq": number; "command": unknown; }>; "cursor": number; };
export type RuntimeReady = { "state": "ready" | "not_ready"; "reason": string | null; "unrecovered": ReadonlyArray<{ "attemptId": string; "reason": string; }>; };
