// Generated by packages/contracts/scripts/generate-specialists.ts from config/specialists.json; do not edit.

/** The specialist roles of the registry: what the bundle composes for each (id, route, native tool policy), with the
 * route as the runtime unit records it (USD per million tokens). */
export const SPECIALISTS = [
  {
    id: 'sophia-research-md-v1',
    family: 'research',
    taskKind: 'research',
    outputs: ['markdown'],
    route: 'research-sol-medium-v1',
    routeSpec: { provider: 'openai-research', model: 'gpt-6.1-sol', reasoningEffort: 'medium', maxTokens: 16000, prices: { input: 2, cacheRead: 0.1, cacheWrite: 2.5, output: 10 } },
    nativeTools: ['todo_write', 'research_read_context', 'research_search', 'research_read_source', 'research_write_draft', 'research_submit_result', 'research_report_blocker'],
  },
  {
    id: 'sophia-research-pdf-v1',
    family: 'research',
    taskKind: 'research',
    outputs: ['markdown', 'pdf'],
    route: 'research-sol-medium-v1',
    routeSpec: { provider: 'openai-research', model: 'gpt-6.1-sol', reasoningEffort: 'medium', maxTokens: 16000, prices: { input: 2, cacheRead: 0.1, cacheWrite: 2.5, output: 10 } },
    nativeTools: ['todo_write', 'research_read_context', 'research_search', 'research_read_source', 'research_write_draft', 'research_render_pdf', 'research_inspect_output', 'research_submit_result', 'research_report_blocker'],
  },
  {
    id: 'sophia-source-review-v1',
    family: 'review',
    taskKind: 'source_review',
    outputs: ['markdown'],
    route: 'source-review-luna-high-v1',
    routeSpec: { provider: 'openai-review', model: 'gpt-6-luna', reasoningEffort: 'high', maxTokens: 16000, prices: { input: 0.1, cacheRead: 0.01, cacheWrite: 0.125, output: 0.5 } },
    nativeTools: ['read_review_source', 'submit_source_review', 'report_review_blocker'],
  },
] as const

export type SpecialistId = (typeof SPECIALISTS)[number]['id']
