// Generated by packages/contracts/scripts/generate-specialists.ts from config/specialists.json; do not edit.

/** The specialist roles of the registry: what the bundle composes for each (id, route, native tool policy). */
export const SPECIALISTS = [
  {
    id: 'sophia-research-md-v1',
    family: 'research',
    outputs: ['markdown'],
    route: 'research-sol-medium-v1',
    nativeTools: ['todo_write', 'research_read_context', 'research_search', 'research_read_source', 'research_write_draft', 'research_inspect_output', 'research_submit_result', 'research_report_blocker'],
  },
  {
    id: 'sophia-research-pdf-v1',
    family: 'research',
    outputs: ['markdown', 'pdf'],
    route: 'research-sol-medium-v1',
    nativeTools: ['todo_write', 'research_read_context', 'research_search', 'research_read_source', 'research_write_draft', 'research_render_pdf', 'research_inspect_output', 'research_submit_result', 'research_report_blocker'],
  },
] as const

export type SpecialistId = (typeof SPECIALISTS)[number]['id']
