#!/usr/bin/env python3
"""Generate dependency-free TypeScript types from this pack's OpenAPI schema subset."""
import json,sys
from pathlib import Path
R=Path(__file__).resolve().parents[1]
doc=json.loads((R/'api/openapi.json').read_text())
def typ(s):
 if '$ref' in s:return s['$ref'].split('/')[-1]
 if 'const' in s:return json.dumps(s['const'])
 if 'enum' in s:return ' | '.join(json.dumps(x) for x in s['enum'])
 if 'anyOf' in s:return ' | '.join(typ(x) for x in s['anyOf'])
 t=s.get('type')
 if t=='null':return 'null'
 if t=='string':return 'string'
 if t in ('integer','number'):return 'number'
 if t=='boolean':return 'boolean'
 if t=='array':return f"ReadonlyArray<{typ(s['items'])}>"
 if t=='object':
  props=s.get('properties',{}); req=s.get('required',[])
  if not props and isinstance(s.get('additionalProperties'),dict):return f"Readonly<Record<string, {typ(s['additionalProperties'])}>>"
  return '{ '+ ' '.join(f'{json.dumps(k)}'+('' if k in req else '?')+': '+typ(v)+';' for k,v in props.items())+' }'
 raise ValueError(f'Unsupported schema: {s}')
lines=['/** Generated by scripts/generate_api_types.py; edit api/openapi.json, not this file. */','/** Format/pattern constraints are runtime validation obligations, not encoded by string types. */']
for n,s in doc['components']['schemas'].items():lines.append(f'export type {n} = {typ(s)};')
ops=[]
for path,methods in doc['paths'].items():
 for method,op in methods.items():
  rb=op.get('requestBody',{}).get('content',{}).get('application/json',{}).get('schema')
  result=next((v for k,v in op['responses'].items() if k.startswith('2')),{}).get('content',{}).get('application/json',{}).get('schema')
  ops.append(f"  {json.dumps(op['operationId'])}: {{ method: {json.dumps(method.upper())}; path: {json.dumps(path)}; request: {typ(rb) if rb else 'undefined'}; response: {typ(result) if result else 'AsyncIterable<Event | CursorAdvance>'}; }};")
lines+=['export interface Operations {',*ops,'}']
text='\n'.join(lines)+'\n';target=R/'api/generated-types.ts'
if '--check' in sys.argv:
 if not target.exists() or target.read_text()!=text:raise SystemExit('Generated API types are out of date')
 print('Generated API types match OpenAPI')
else:target.write_text(text)
