#!/usr/bin/env node
// Provision the local Supabase stack for sophia-next (Docker; no cloud account involved):
//   1. local ES256 JWT signing key (supabase/signing_keys.json, gitignored)
//   2. `supabase start` with only db, auth, gateway and Mailpit
//   3. db/migrations through the checksum-ledger runner, as the migration owner
//   4. the API login, with a fresh random password each run
//   5. .env.supabase.local (API + live tests) and apps/studio/.env.development.local (browser)
// The keys printed by `supabase status` are Supabase's documented local-development defaults.
//   node scripts/supabase-local.ts
import { spawnSync } from 'node:child_process'
import { randomBytes } from 'node:crypto'
import { existsSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { migrate } from '../packages/persistence/src/migrate.ts'
import { apiLoginUrl, provisionApiLogin } from './lib/api-login.ts'

process.chdir(fileURLToPath(new URL('..', import.meta.url)))
const CLI = 'npx -y supabase@2.117.0'
const EXCLUDED_SERVICES = 'realtime,storage-api,imgproxy,studio,postgres-meta,edge-runtime,logflare,vector,supavisor'
const SIGNING_KEYS = 'supabase/signing_keys.json'

interface SupabaseStatus {
  API_URL: string
  DB_URL: string
  PUBLISHABLE_KEY: string
  SECRET_KEY: string
  MAILPIT_URL: string
}

/** The CLI is an npx shim (a shell is needed on Windows); arguments are fixed constants. */
function supabase(args: string): string {
  const r = spawnSync(`${CLI} ${args}`, { encoding: 'utf8', shell: true })
  if (r.status !== 0) throw new Error(`supabase ${args} failed:\n${r.stderr || r.stdout}`)
  return r.stdout
}

if (!existsSync(SIGNING_KEYS)) {
  writeFileSync(SIGNING_KEYS, '[]')
  supabase('gen signing-key --algorithm ES256 --append')
  console.log('✓ generated local ES256 signing key')
}

supabase(`start -x ${EXCLUDED_SERVICES}`)
const status = JSON.parse(supabase('status -o json').replace(/^[^{]*/, '')) as SupabaseStatus
console.log(`✓ Supabase local: API ${status.API_URL} · DB ${status.DB_URL.replace(/:[^:@]+@/, ':***@')}`)

const report = await migrate(status.DB_URL, 'db/migrations')
const applied = report.rows.filter((r) => r.status === 'applied').length
console.log(`✓ migrations: ${applied} applied, ${report.rows.length - applied} already applied`)

const password = randomBytes(16).toString('hex')
await provisionApiLogin(status.DB_URL, password)
console.log('✓ API login provisioned (member of sophia_api, no BYPASSRLS)')

// Dev-only, gitignored (.env.*). The secret key is the local default, used only by the live test
// suite to create synthetic users in this local Auth.
const env = {
  SOPHIA_API_DATABASE_URL: apiLoginUrl(status.DB_URL, password),
  SOPHIA_MIGRATION_DATABASE_URL: status.DB_URL,
  SUPABASE_URL: status.API_URL,
  SUPABASE_JWT_ISSUER: `${status.API_URL}/auth/v1`,
  SUPABASE_JWKS_URL: `${status.API_URL}/auth/v1/.well-known/jwks.json`,
  SUPABASE_PUBLISHABLE_KEY: status.PUBLISHABLE_KEY,
  SUPABASE_TEST_ADMIN_KEY: status.SECRET_KEY,
  MAILPIT_URL: status.MAILPIT_URL,
}
const envFile = (entries: Record<string, string>, header?: string) =>
  [...(header ? [header] : []), ...Object.entries(entries).map(([k, v]) => `${k}=${v}`), ''].join('\n')

writeFileSync(
  '.env.supabase.local',
  envFile(env, '# Generated by scripts/supabase-local.ts — local Supabase only. Do not copy to hosted environments.'),
)
writeFileSync(
  'apps/studio/.env.development.local',
  envFile({ VITE_SUPABASE_URL: status.API_URL, VITE_SUPABASE_PUBLISHABLE_KEY: status.PUBLISHABLE_KEY }),
)
console.log(`✓ wrote .env.supabase.local and apps/studio/.env.development.local`)
console.log(`  Sign-in emails arrive in Mailpit: ${status.MAILPIT_URL}`)
