// @sophia/persistence — Postgres access for the API and worker.
// Runs as a login granted `sophia_api` (never the migration owner or a service-role key).
export {
  createPool,
  checkRoleSafety,
  withActor,
  withoutActor,
  withService,
  type PoolOptions,
  type TxMode,
} from './tx.ts'
export { classifyDbError } from './errors.ts'
export { migrate, readMigrations, MigrationDrift, type MigrationReport } from './migrate.ts'
export { readSnapshot } from './snapshot.ts'
export { admitGoalCommand, commandKeyUsed } from './commands.ts'
export { createProject } from './projects.ts'
export { authorizeRoomJoin, transferInputFloor, type MemberRole } from './room.ts'
export {
  acceptRoomInvitation,
  authorizeGuestJoin,
  guestTokenMinting,
  cancelRoomSession,
  createRoomInvitation,
  decideLobbyEntry,
  knockRoom,
  listInvitations,
  previewRoomInvitation,
  readInvitation,
  readLobbyEntry,
  readMembership,
  recordInvitationEmail,
  reissueRoomInvitation,
  revokeRoomInvitation,
  scheduleRoomSession,
  type InvitationRecord,
  type InvitationRequest,
  type LobbyRecord,
  type NewInvitation,
} from './access.ts'
export { claimOutbox, expireDispatchLeases, recordDispatchResult, type OutboxRow } from './outbox.ts'
export { readEventFrames, type EventFrame, type EventPage } from './events.ts'
export {
  ChannelListener,
  ProjectEventListener,
  PROJECT_EVENTS_CHANNEL,
  RUNTIME_COMMANDS_CHANNEL,
  type ChannelHandlers,
  type ListenHandlers,
} from './listen.ts'
export {
  recordRuntimeObservations,
  recordRuntimeReady,
  recordRuntimeReceipts,
  runtimeHello,
  runtimePoll,
  runtimeTokenHash,
  type RuntimeCaller,
} from './runtime.ts'
export {
  admitResearchTask,
  researchGateOpen,
  runtimeResearchCapture,
  runtimeResearchContext,
  runtimeResearchDraft,
  runtimeResearchReserve,
  runtimeResearchSettle,
  runtimeResearchSubmit,
  type ResearchAdmission,
  type ResearchAdmissionCall,
  type ResearchAdmissionRequest,
  type ResearchSpecialist,
} from './research.ts'
export {
  pdfRendererReady,
  requestResearchRendition,
  runtimeResearchRender,
  runtimeResearchRenderResult,
} from './research-render.ts'
export {
  admitNativeTask,
  readDiscussion,
  readNativeTask,
  readNativeTasks,
  readResearchVersion,
  readTaskStandings,
  submitContribution,
  type ContributionOrigin,
  type ReportVersion,
  type ReportVersionText,
  type ResearchVersions,
  type SectionCounts,
  type TaskStanding,
} from './native-tasks.ts'
export {
  editReportSummary,
  listReports,
  listReportSources,
  readArtifactVersions,
  readReportSource,
  REPORT_PAGE,
  searchQuery,
  type ReportQuery,
  type ReportSource,
} from './artifacts.ts'
export {
  enqueueRenderJob,
  rendererClaim,
  rendererFile,
  rendererHeartbeat,
  rendererOutputSlot,
  rendererRecordOutput,
  rendererSettle,
  type RecordedOutput,
  type RenderFileLocation,
  type RenderPackageFile,
} from './renderer.ts'
export { claimRuntimeOutbox, dispatchRuntimeOutbox, reconcileRuntimeOutbox, type DispatchOutcome } from './dispatch.ts'
export {
  ackQuiesce,
  controlExchange,
  holderEvent,
  mediaAssignments,
  PRESENCE_FRESH_SECONDS,
  quiesceAcked,
  readSophia,
  recordAnnounced,
  reportPresence,
  requestGuestQuiesce,
  startExchange,
  toolSpeaker,
  type ExchangeAction,
  type PresenceReport,
} from './exchange.ts'
export {
  claimRoomRemovals,
  pendingRemoval,
  readRemoval,
  settleRoomRemoval,
  type RemovalClaim,
  type RemovalOutcome,
  type RemovalState,
} from './removals.ts'
export {
  decideMissionChange,
  presentMissionProposal,
  previewMissionWithdrawal,
  proposeMissionChange,
  recordMissionEntry,
  setMissionNoteConsent,
  setMissionNotePolicy,
  shownReach,
  withdrawMissionEntry,
  type DecisionWrite,
  type MissionTurn,
  type NoteWrite,
  type Presented,
  type ProposalWrite,
} from './mission.ts'
export {
  MISSION_CONTEXT_COMPILER,
  readConfirmationTarget,
  readMissionContext,
  readMissionSource,
  TRANSCRIPT_BUFFER,
  type ConfirmationTarget,
  type MissionReader,
  type MissionSource,
} from './mission-context.ts'
export {
  carryPersonalNote,
  decidePersonalSuggestion,
  erasePersonalSpace,
  failPersonalReply,
  fencePersonalWrite,
  forgetErasedCompanionCalls,
  forgetPersonalNote,
  keepPersonalNote,
  PERSONAL_PAGE_LIMIT,
  PERSONAL_TURN_LIMIT,
  nextPersonalReply,
  readCompanionContext,
  readPersonalEpoch,
  readPersonalExport,
  beginCompanionCall,
  beginPersonalGreeting,
  claimPersonalReply,
  endCompanionCall,
  erasedCompanionCalls,
  readPersonalSpace,
  readPersonalTurnsAfter,
  readPersonalTurnsBefore,
  readWelcomeContext,
  recordPersonalGreeting,
  recordPersonalReply,
  releasePersonalGreeting,
  renewPersonalGreeting,
  renewPersonalReply,
  replayPersonalGreeting,
  replayPersonalRetry,
  replayPersonalTurn,
  retryPersonalTurn,
  sendPersonalTurn,
  takeBackPersonalRelease,
  type CompanionContext,
} from './personal.ts'
export { listProjects, PROJECT_LIST_BOUNDS, type ProjectListing } from './project-list.ts'
